title: "Dr. Yejin Kim"
description: "AI for Healthcare"
baseurl: ""
url: "https://yejinjkim.github.io"
theme: minima # or any other Jekyll theme
markdown: kramdown

# Optional: if you want a navigation menu
header_pages:
  - title: "Home"
    url: "/"
  - title: "Professor"
    url: "/professor"
  - title: "Team"
    url: "/team"
  - title: "Research"
    url: "/research"
  - title: "Lectures"
    url: "/lectures"
  - title: "Funding"
    url: "/funding"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
